abcdef/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('app.urls')),
]

app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views
from django.views.generic import TemplateView

urlpatterns = [
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    
    # url(r'^$', views.home, name="home"),
    url(r'^page(?P<id>[0-9]+)/$', views.page, name="page"),
    url(r'^event/type/([^/]+)/$', views.event_type, name='events'),
    url(r'^$', views.event_home, name='eventhome'),
    url(r'^events/', include('swingtime.urls')),
]

swingtime/urls.py
from django.conf.urls import url
from swingtime import views

urlpatterns = [
    url(
        r'^(?:calendar/)?$', 
        views.today_view, 
        name='swingtime-today'
    ),

    url(
        r'^calendar/(?P<year>\d{4})/$', 
        views.year_view, 
        name='swingtime-yearly-view'
    ),

    url(
        r'^calendar/(\d{4})/(0?[1-9]|1[012])/$', 
        views.month_view, 
        name='swingtime-monthly-view'
    ),

    url(
        r'^calendar/(\d{4})/(0?[1-9]|1[012])/([0-3]?\d)/$', 
        views.day_view, 
        name='swingtime-daily-view'
    ),

    url(
        r'^events/$',
        views.event_listing,
        name='swingtime-events'
    ),
        
    url(
        r'^events/add/$', 
        views.add_event, 
        name='swingtime-add-event'
    ),
    
    url(
        r'^events/(\d+)/$', 
        views.event_view, 
        name='swingtime-event'
    ),
    
    url(
        r'^events/(\d+)/(\d+)/$', 
        views.occurrence_view, 
        name='swingtime-occurrence'
    ),
]

swingtime/forms.py
'''
Convenience forms for adding and updating ``Event`` and ``Occurrence``s.

'''
from __future__ import print_function, unicode_literals
from datetime import datetime, date, time, timedelta
from django import VERSION
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.forms.extras.widgets import SelectDateWidget

from dateutil import rrule
from swingtime.conf import settings as swingtime_settings
from swingtime.models import *
from swingtime import utils

FIELDS_REQUIRED = (VERSION[:2] >= (1, 6))

WEEKDAY_SHORT = (
    (7, _('Sun')),
    (1, _('Mon')),
    (2, _('Tue')),
    (3, _('Wed')),
    (4, _('Thu')),
    (5, _('Fri')),
    (6, _('Sat'))
)

WEEKDAY_LONG = (
    (7, _('Sunday')),
    (1, _('Monday')),
    (2, _('Tuesday')),
    (3, _('Wednesday')),
    (4, _('Thursday')),
    (5, _('Friday')),
    (6, _('Saturday'))
)

MONTH_LONG = (
    (1,  _('January')),
    (2,  _('February')),
    (3,  _('March')),
    (4,  _('April')),
    (5,  _('May')),
    (6,  _('June')),
    (7,  _('July')),
    (8,  _('August')),
    (9,  _('September')),
    (10, _('October')),
    (11, _('November')),
    (12, _('December')),
)

MONTH_SHORT = (
    (1,  _('Jan')),
    (2,  _('Feb')),
    (3,  _('Mar')),
    (4,  _('Apr')),
    (5,  _('May')),
    (6,  _('Jun')),
    (7,  _('Jul')),
    (8,  _('Aug')),
    (9,  _('Sep')),
    (10, _('Oct')),
    (11, _('Nov')),
    (12, _('Dec')),
)


ORDINAL = (
    (1,  _('first')),
    (2,  _('second')),
    (3,  _('third')),
    (4,  _('fourth')),
    (-1, _('last'))
)

FREQUENCY_CHOICES = (
    (rrule.DAILY,   _('Day(s)')),
    (rrule.WEEKLY,  _('Week(s)')),
    (rrule.MONTHLY, _('Month(s)')),
    (rrule.YEARLY,  _('Year(s)')),
)

REPEAT_CHOICES = (
    ('count', _('By count')),
    ('until', _('Until date')),
)

ISO_WEEKDAYS_MAP = (
    None,
    rrule.MO,
    rrule.TU,
    rrule.WE,
    rrule.TH,
    rrule.FR,
    rrule.SA,
    rrule.SU
)

MINUTES_INTERVAL = swingtime_settings.TIMESLOT_INTERVAL.seconds // 60
SECONDS_INTERVAL = utils.time_delta_total_seconds(swingtime_settings.DEFAULT_OCCURRENCE_DURATION)

#-------------------------------------------------------------------------------
def timeslot_options(
    interval=swingtime_settings.TIMESLOT_INTERVAL,
    start_time=swingtime_settings.TIMESLOT_START_TIME,
    end_delta=swingtime_settings.TIMESLOT_END_TIME_DURATION,
    fmt=swingtime_settings.TIMESLOT_TIME_FORMAT
):
    '''
    Create a list of time slot options for use in swingtime forms.

    The list is comprised of 2-tuples containing a 24-hour time value and a
    12-hour temporal representation of that offset.

    '''
    dt = datetime.combine(date.today(), time(0))
    dtstart = datetime.combine(dt.date(), start_time)
    dtend = dtstart + end_delta
    options = []

    while dtstart <= dtend:
        options.append((str(dtstart.time()), dtstart.strftime(fmt)))
        dtstart += interval

    return options

#-------------------------------------------------------------------------------
def timeslot_offset_options(
    interval=swingtime_settings.TIMESLOT_INTERVAL,
    start_time=swingtime_settings.TIMESLOT_START_TIME,
    end_delta=swingtime_settings.TIMESLOT_END_TIME_DURATION,
    fmt=swingtime_settings.TIMESLOT_TIME_FORMAT
):
    '''
    Create a list of time slot options for use in swingtime forms.

    The list is comprised of 2-tuples containing the number of seconds since the
    start of the day and a 12-hour temporal representation of that offset.

    '''
    dt = datetime.combine(date.today(), time(0))
    dtstart = datetime.combine(dt.date(), start_time)
    dtend = dtstart + end_delta
    options = []

    delta = utils.time_delta_total_seconds(dtstart - dt)
    seconds = utils.time_delta_total_seconds(interval)
    while dtstart <= dtend:
        options.append((delta, dtstart.strftime(fmt)))
        dtstart += interval
        delta += seconds

    return options

default_timeslot_options = timeslot_options()
default_timeslot_offset_options = timeslot_offset_options()


#===============================================================================
class MultipleIntegerField(forms.MultipleChoiceField):
    '''
    A form field for handling multiple integers.

    '''

    #---------------------------------------------------------------------------
    def __init__(self, choices, size=None, label=None, widget=None):
        if widget is None:
            widget = forms.SelectMultiple(attrs={'size' : size or len(choices)})
        super(MultipleIntegerField, self).__init__(
            required=False,
            choices=choices,
            label=label,
            widget=widget,
        )

    #---------------------------------------------------------------------------
    def clean(self, value):
        return [int(i) for i in super(MultipleIntegerField, self).clean(value)]


#===============================================================================
class SplitDateTimeWidget(forms.MultiWidget):
    '''
    A Widget that splits datetime input into a SelectDateWidget for dates and
    Select widget for times.

    '''
    #---------------------------------------------------------------------------
    def __init__(self, attrs=None):
        widgets = (
            SelectDateWidget(attrs=attrs),
            forms.Select(choices=default_timeslot_options, attrs=attrs)
        )
        super(SplitDateTimeWidget, self).__init__(widgets, attrs)

    #---------------------------------------------------------------------------
    def decompress(self, value):
        if value:
            return [value.date(), value.time().replace(microsecond=0)]

        return [None, None]


#===============================================================================
class MultipleOccurrenceForm(forms.Form):
    day = forms.DateField(
        label=_('Date'),
        initial=date.today,
        widget=SelectDateWidget()
    )

    start_time_delta = forms.IntegerField(
        label=_('Start time'),
        widget=forms.Select(choices=default_timeslot_offset_options)
    )

    end_time_delta = forms.IntegerField(
        label=_('End time'),
        widget=forms.Select(choices=default_timeslot_offset_options)
    )

    # recurrence options
    repeats = forms.ChoiceField(
        choices=REPEAT_CHOICES,
        initial='count',
        label=_('Occurrences'),
        widget=forms.RadioSelect()
    )

    count = forms.IntegerField(
        label=_('Total Occurrences'),
        initial=1,
        required=False,
        widget=forms.TextInput(attrs=dict(size=2, max_length=2))
    )

    until = forms.DateField(
        required=False,
        initial=date.today,
        widget=SelectDateWidget()
    )

    freq = forms.IntegerField(
        label=_('Frequency'),
        initial=rrule.WEEKLY,
        widget=forms.RadioSelect(choices=FREQUENCY_CHOICES),
    )

    interval = forms.IntegerField(
        required=False,
        initial='1',
        widget=forms.TextInput(attrs=dict(size=3, max_length=3))
    )

    # weekly options
    week_days = MultipleIntegerField(
        WEEKDAY_SHORT,
        label=_('Weekly options'),
        widget=forms.CheckboxSelectMultiple
    )

    # monthly  options
    month_option = forms.ChoiceField(
        choices=(('on',_('On the')), ('each',_('Each:'))),
        initial='each',
        widget=forms.RadioSelect(),
        label=_('Monthly options')
    )

    month_ordinal = forms.IntegerField(widget=forms.Select(choices=ORDINAL), required=False)
    month_ordinal_day = forms.IntegerField(widget=forms.Select(choices=WEEKDAY_LONG), required=False)
    each_month_day = MultipleIntegerField(
        [(i,i) for i in range(1,32)],
        widget=forms.CheckboxSelectMultiple
    )

    # yearly options
    year_months = MultipleIntegerField(
        MONTH_SHORT,
        label=_('Yearly options'),
        widget=forms.CheckboxSelectMultiple
    )

    is_year_month_ordinal = forms.BooleanField(required=False)
    year_month_ordinal = forms.IntegerField(widget=forms.Select(choices=ORDINAL), required=False)
    year_month_ordinal_day = forms.IntegerField(widget=forms.Select(choices=WEEKDAY_LONG), required=False)

    #---------------------------------------------------------------------------
    def __init__(self, *args, **kws):
        super(MultipleOccurrenceForm, self).__init__(*args, **kws)
        dtstart = self.initial.get('dtstart', None)
        if dtstart:
            dtstart = dtstart.replace(
                minute=((dtstart.minute // MINUTES_INTERVAL) * MINUTES_INTERVAL),
                second=0,
                microsecond=0
            )

            weekday = dtstart.isoweekday()
            ordinal = dtstart.day // 7
            ordinal = '%d' % (-1 if ordinal > 3 else ordinal + 1,)
            offset = (dtstart - datetime.combine(dtstart.date(), time(0, tzinfo=dtstart.tzinfo))).seconds

            self.initial.setdefault('day', dtstart)
            self.initial.setdefault('week_days', '%d' % weekday)
            self.initial.setdefault('month_ordinal', ordinal)
            self.initial.setdefault('month_ordinal_day', '%d' % weekday)
            self.initial.setdefault('each_month_day', ['%d' % dtstart.day])
            self.initial.setdefault('year_months', ['%d' % dtstart.month])
            self.initial.setdefault('year_month_ordinal', ordinal)
            self.initial.setdefault('year_month_ordinal_day', '%d' % weekday)
            self.initial.setdefault('start_time_delta', '%d' % offset)
            self.initial.setdefault('end_time_delta', '%d' % (offset + SECONDS_INTERVAL,))

    #---------------------------------------------------------------------------
    def clean(self):
        day = datetime.combine(self.cleaned_data['day'], time(0))
        self.cleaned_data['start_time'] = day + timedelta(
            seconds=self.cleaned_data['start_time_delta']
        )

        self.cleaned_data['end_time'] = day + timedelta(

app/templates/swingtime/add_event.html
{% extends "base.html" %}
{% block title %}Add Event{% endblock %}
{% block main_content %}
    <h3>Add Event</h3>
    {{ event_form.non_field_errors }}
    {{ recurring_form.non_field_errors }}
    {% if event_form.errors or recurrence_form.errors %}
    <p class="form-errors">Please fix any errors.</p>
    {% endif %}
    <form method="post" action="">
    <table>
        <tfoot>
            <tr>
                <td colspan="2"><input type="submit" value="Submit" /></td>
            </tr>
        </tfoot>
        <tbody>
        {% include "swingtime/event_form_part.html" %}
        {% include "swingtime/recurring_form_part.html" %}
        </tbody>
    </table>
    </form>

{% endblock %}

app/templates/swingtime/daily_view.html
{% extends "base.html" %}
{% block title %}Daily View{% endblock %}
{% block main_content %}
    <h3>Daily View</h3>
    <h4>
        <a class="plain" href="{% url 'swingtime-daily-view' prev_day.year prev_day.month prev_day.day %}">&larr;</a>
        {{ day|date:"l, N jS Y" }}
        <a class="plain" href="{% url 'swingtime-daily-view' next_day.year next_day.month next_day.day %}">&rarr;</a>
    </h4>
    <table class="calendar">
        <thead>
            <tr>
                <th>Time</th>
                <th>Main Room</th>
                <th>Private 2</th>
                <th>Private 3</th>
                <th colspan="4">Private 4</th>
            </tr>
        </thead>
        <tbody>
            {% for tm,cells in timeslots %}
            <tr>
                <th><a href="{% url 'swingtime-add-event' %}?dtstart={{ tm.isoformat }}">{{ tm|date:"P" }}</a></th>
                {% for cell in cells %}
                <td{% if cell.event_class %} class="{{cell.event_class}}"{% endif %}>{{ cell }}</td>    
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/swingtime/event_detail.html
{% extends "base.html" %}
{% block title %}Event: {{ event }}{% endblock %}
{% block main_content %}
    <h3>Swingtime Event</h3>
    <h4>Event Details</h4>
    <form action="" method="post">
    <table>
        <tfoot>
            <tr>
                <td colspan="2">
                    <input type="submit" name="_update" value="Update" />
                </td>
            </tr>
        </tfoot>
        <tbody>
        {% include "swingtime/event_form_part.html" %}
        </tbody>
    </table>
    </form>
    
    <h4>Notes</h4>
    {% with event.notes.all as notes %}
    {% if notes %}
    <ul>
        {% for note in notes %}
        <li>{{ note }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>None</p>
    {% endif %}
    {% endwith %}

    <h4>Occurrences</h4>
    {% if event.occurrence_set.count %}
    <ol>
        {% for o in event.occurrence_set.all %}
        <li>
            {% if o.start_time.date == o.end_time.date %}
            <a href="{% url 'swingtime-occurrence' event.id o.id %}">
                {{ o.start_time|date:"l, F jS, Y" }} {{ o.start_time|date:"P" }} &ndash; {{ o.end_time|date:"P" }}</a>
            {% else %}
            <a href="{% url 'swingtime-occurrence' event.id o.id %}">
                {{ o.start_time|date:"l, F jS, Y P" }} &ndash; 
                {{ o.end_time|date:"l, F jS, Y P" }}</a>
            {% endif %}
        </li>
        {% endfor %}
    </ol>
    {% else %}
    {% endif %}
    
    <h4>Add Occurrences</h4>
    <form action="" method="post">
    <table>
        <tfoot>
            <tr>
                <td colspan="2"><input type="submit" name="_add" value="Add" /></td>
            </tr>
        </tfoot>
        <tbody>
        {% include "swingtime/recurring_form_part.html" %}
        </tbody>
    </table>
    </form>
    </form>
{% endblock %}

app/templates/swingtime/event_form_part.html
        <tr><th>{{ event_form.event_type.label_tag }}</th>
            <td>{{ event_form.event_type.errors }}
                {{ event_form.event_type }}</td></tr>
        <tr><th>{{ event_form.title.label_tag }}</th>
            <td>{{ event_form.title.errors }}
                {{ event_form.title }}</td></tr>
        <tr><th>{{ event_form.description.label_tag }}</th>
            <td>{{ event_form.description }}</td></tr>

app/templates/swingtime/event_list.html
{% extends "base.html" %}
{% block title %}All Events{% endblock %}
{% block main_content %}
    <h3>All Events</h3>
    <ul>{% for e in events %}
        <li><a href="{{ e.get_absolute_url }}">{{ e }}</a></li>
    {% endfor %}</ul>
{% endblock %}

app/templates/swingtime/eventhome.html
{% extends "base.html" %}
{% block main_content %}
<div class="center">
    <h3>Welcome to a giving community!</h3>
    <p>Check out our opportunities to help</p>

    <h3>Opportunities</h3>
    <p>Select the link below to see upcoming events:</p>
    <ul id="belts">
    {% for event in event_type %}
        <li><a href="{% url 'events' event.abbr %}" >{{ event.label }}</a></li>
    {% endfor %}
    </ul>
</div>
{% endblock main_content %}

app/templates/swingtime/monthly_view.html
{% extends "base.html" %}
{% block title %}Monthly View{% endblock %}
{% block main_content %}
    <h3>Monthly View</h3>
    <h4>
        <a href="{% url 'swingtime-monthly-view' last_month.year last_month.month %}" 
           title="Last Month">&larr;</a>
        {{ this_month|date:"F" }}
        <a title="View {{ this_month.year}}" href="{% url 'swingtime-yearly-view' this_month.year %}">
            {{ this_month|date:"Y" }}</a>
        <a href="{% url 'swingtime-monthly-view' next_month.year next_month.month %}" 
           title="Next Month">&rarr;</a>
    </h4>
    <table class="month-view">
        <thead>
            <tr>
                <th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th>
            </tr>
        </thead>
        <tbody>
            {% for row in calendar %}
            <tr>
                {% for day,items in row  %}
                <td{% ifequal day today.day  %} class="today"{% endifequal %}>
                {% if day %}
                    <div class="day-ordinal">
                        <a href="{% url 'swingtime-daily-view' this_month.year this_month.month day %}">{{ day }}</a>
                    </div>
                    {% if items %}
                    <ul>
                        {% for item in items %}
                        <li>
                            <a href="{{ item.get_absolute_url }}">
                                <span class="event-times">{{ item.start_time|time }}</span>
                                {{ item.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/swingtime/occurrence_detail.html
{% extends "base.html" %}
{% block title %}Event Occurrence{% endblock %}
{% block main_content %}
     <h3>Swingtime Event Occurrence</h3>
     <h4>
         <a href="{{ occurrence.event.get_absolute_url }}">{{ occurrence.title }}</a>
         &ndash;
         {% with occurrence.start_time as st  %}
         <a href="{% url 'swingtime-daily-view' st.year st.month st.day %}">
            {{ st|date:"l, F jS P" }}</a>
        </h4>
        {% endwith %}
     <dl>
         <dt>Event type:</dt>
         <dd>{{ occurrence.event.event_type }}</dd>
         
         <dt>Description:</dt>
         <dd>{{ occurrence.event.description|default:"None" }}</dd>
         
         <dt>Note(s:)</dt>
         <dd>
             {% with occurrence.event.notes.all as notes %}
             {% if notes %}
             <ul>
                 {% for note in notes %}
                 <li>{{ note }}</li>
                 {% endfor %}
             </ul>
             {% else %}None
             {% endif %}
             {% endwith %}
         </dd>
     </dl>
     
     <form action="" method="post">
     <table>
         <tfoot>
             <tr>
                 <td colspan="2"><input type="submit" value="Update" /></td>
             </tr>
         </tfoot>
         <tbody>
             {{ form }}
         </tbody>
     </table>
     </form>

{% endblock %}

app/templates/swingtime/recurring_form_part.html
        <tr><th>{{ recurrence_form.day.label_tag}}</th>
            <td>{{ recurrence_form.day }}</td></tr>
        <tr><th>{{ recurrence_form.start_time_delta.label_tag }}</th>
            <td>{{ recurrence_form.start_time_delta }}</td></tr>
        <tr><th>{{ recurrence_form.end_time_delta.label_tag }}</th>
            <td>{{ recurrence_form.end_time_delta }}</td></tr>

        <tr><th>{{ recurrence_form.repeats.label_tag }}</th>
            <td>
                {{ recurrence_form.count.errors }}
                <ul>
                    <li><label for="id_repeats_0">
                        <input checked="checked" type="radio" id="id_repeats_0" 
                            value="count" name="repeats" /> A total of</label>
                        {{ recurrence_form.count }} time(s)</li>
                    <li><label for="id_repeats_1">
                        <input type="radio" id="id_repeats_1" value="until" 
                            name="repeats" /> Until </label>
                        {{ recurrence_form.until }}</li>
                </ul></td></tr>

        <tr><th>{{ recurrence_form.freq.label_tag }}</th>
            <td>
                {{ recurrence_form.interval.errors }}
                <div style="float: left">Every {{ recurrence_form.interval }} </div>
                <ul id="recurrence-options">
                    <li><label for="id_freq_0">
                        <input type="radio" id="id_freq_0" 
                            value="3" name="freq" /> Day(s)</label>
                    </li>
                    <li>
                        <label for="id_freq_1">
                            <input checked="checked" type="radio" id="id_freq_1" 
                                value="2" name="freq" /> Week(s):</label>
                        <div class="horizontal form-indent">
                            {{ recurrence_form.week_days }}
                        </div>
                        <br clear="all" />
                    </li>
                    <li>
                        <label for="id_freq_2">
                            <input type="radio" id="id_freq_2" 
                                value="1" name="freq" /> Month(s)</label>
                        <div class="form-indent">
                            <ul>
                                <li>
                                    <label for="id_month_option_0">
                                        <input type="radio" id="id_month_option_0" 
                                            value="on" name="month_option" /> 
                                        On the</label>
                                    {{ recurrence_form.month_ordinal }}
                                    {{ recurrence_form.month_ordinal_day }}
                                </li>
                                <li>
                                    <label for="id_month_option_1">
                                        <input checked="checked" type="radio" 
                                            id="id_month_option_1" value="each" 
                                            name="month_option" /> Each:</label>
                                    <br clear="all" />
                                    <div class="horizontal form-indent">
                                        {{ recurrence_form.each_month_day }}
                                    </div>
                                    <br clear="all" />
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <label for="id_freq_3">
                            <input type="radio" id="id_freq_3" 
                                value="0" name="freq" /> Year(s)</label>
                        <div class="form-indent">
                            <div class="horizontal">
                                {{ recurrence_form.year_months}} 
                            </div>
                            <br clear="all" />
                            <div class="form-indent">
                            <label for="id_is_year_month_ordinal">
                                {{ recurrence_form.is_year_month_ordinal }} 
                                On the </label>
                            
                            {{ recurrence_form.year_month_ordinal }}
                            {{ recurrence_form.year_month_ordinal_day }}
                            </div>
                        </div>
                    </li>
                </ul>
            </td>
        </tr>

app/templates/swingtime/upcoming_by_event_type.html
{% extends "base.html" %}
{% block title %}Upcoming {{ event_type }} Events{% endblock %}
{% block main_content %}
    <h3>Upcoming {{ event_type }} </h3>
    <ul>
        {% for o in occurrences %}
            <li>
                {{ o.title }}
                <a href="{{ o.get_absolute_url }}">{{ o.start_time|date:"D, M jS P" }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/swingtime/yearly_view.html
{% extends "base.html" %}
{% block title %}Yearly View {{ year }}{% endblock %}
{% block main_content %}
    <h3>
        <a href="{% url 'swingtime-yearly-view' last_year %}" 
           title="Last Month">&larr;</a>
        Yearly View {{ year }}
        <a href="{% url 'swingtime-yearly-view' next_year %}" 
           title="Next Month">&rarr;</a>
    </h3>
    
    {% if by_month %}
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Title</th>
                <th>Day</th>
                <th>Start</th>
                <th>End</th>
            </tr>
        </thead>
        <tbody>
        {% for dt,occurrences in by_month %}
        <tr class="month-divider">
            <th rowspan="{{ occurrences|length }}">
                <a href="{% url 'swingtime-monthly-view' dt.year dt.month %}">
                    {{ dt|date:"F" }}</a>
            </th>
            {% for o in occurrences %}
            <td><a href="{{ o.get_absolute_url }}">{{ o.title }}</a></td>
            <td>{{ o.start_time|date:"M jS - l" }}</td>
            <td>{{ o.start_time|date:"P" }}</td>
            <td>{{ o.end_time|date:"P" }}</td>
        </tr>
            {% if not forloop.last %}
        <tr>
            {% endif %}
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No events occurring in {{ year }}</p>
    {% endif %}
{% endblock %}